const crypto=require('node:crypto');const bcrypt=require('bcrypt');const Input=require('../domain/OperationInput');const {RecordError}=require('../domain/RecordInput');
class UserService{
 constructor(repository,{hasher=bcrypt}={}){this.repository=repository;this.hasher=hasher;}
 list(query){const input=Input.page(query,['name','username','role','state']);return this.repository.list(input);}
 async detail(id){const row=await this.repository.detail(Input.id(id));if(!row)throw new RecordError(404,'El usuario no existe.');return row;}
 async create(actor,key,body){const data=Input.userCreate(body),userId=Input.id(actor.idUsuario),op=Input.key(key),request={...data,password:crypto.createHash('sha256').update(data.password).digest('hex')},hash=crypto.createHash('sha256').update(JSON.stringify(['user:create',request])).digest('hex');try{return await this.repository.write({userId,key:op,hash},async c=>{if(await this.repository.username(c,data.username))throw new RecordError(409,'Ese nombre de usuario ya está registrado.',{username:'Elige otro nombre de usuario.'});const passwordHash=await this.hasher.hash(data.password,12);const id=await this.repository.insert(c,data,passwordHash);return {id};});}catch(error){if(error instanceof RecordError)throw error;if(error.code==='ER_DUP_ENTRY')throw new RecordError(409,'Ese nombre de usuario ya está registrado.');throw error;}}
 async update(actor,key,id,body){const data=Input.userUpdate(body),targetId=Input.id(id),userId=Input.id(actor.idUsuario),op=Input.key(key),request={...data,password:data.password?crypto.createHash('sha256').update(data.password).digest('hex'):''},hash=crypto.createHash('sha256').update(JSON.stringify(['user:update',targetId,request])).digest('hex');return this.repository.write({userId,key:op,hash},async c=>{const current=await this.repository.detail(targetId,c,true);if(!current)throw new RecordError(404,'El usuario no existe.');if(targetId===userId&&(data.state!=='ACTIVO'||data.role!==current.role))throw new RecordError(409,'No puedes desactivar tu propia cuenta ni cambiar tu propio rol.');if(await this.repository.username(c,data.username,targetId))throw new RecordError(409,'Ese nombre de usuario ya está registrado.',{username:'Elige otro nombre de usuario.'});if(current.role==='ADMINISTRADOR'&&current.state==='ACTIVO'&&(data.role!=='ADMINISTRADOR'||data.state!=='ACTIVO')){const admins=await this.repository.activeAdmins(c);if(admins.length<=1)throw new RecordError(409,'Debe quedar al menos un administrador activo.');}const passwordHash=data.password?await this.hasher.hash(data.password,12):'';await this.repository.update(c,targetId,data,passwordHash);return {id:targetId};});}
}
module.exports=UserService;
